# --- LDMS sampler config ---
load name=procnetdev
config name=procnetdev producer=${LDMS_NODE} instance=${LDMS_NODE}/netmon ifaces=eth0
start name=procnetdev interval=1000000
load name=meminfo
config name=meminfo producer=${LDMS_NODE} instance=${LDMS_NODE}/memmon
start name=meminfo interval=1000000
load name=vmstat
config name=vmstat producer=${LDMS_NODE} instance=${LDMS_NODE}/vmmon
start name=vmstat interval=1000000
load name=loadavg
config name=loadavg producer=${LDMS_NODE} instance=${LDMS_NODE}/loadavg
start name=loadavg interval=1000000
load name=procdiskstats
config name=procdiskstats producer=${LDMS_NODE} instance=${LDMS_NODE}/diskmon devices=ALL
start name=procdiskstats interval=1000000

load name=syspapi_sampler
config name=syspapi_sampler producer=${LDMS_NODE} instance=${LDMS_NODE}/syspapi \
      events=PAPI_L1_DCM,PAPI_L2_DCM,PAPI_L2_ICM,PAPI_TLB_DM,PAPI_TLB_IM, \
             PAPI_BR_UCN,PAPI_BR_CN,PAPI_BR_TKN,PAPI_BR_NTK,PAPI_BR_MSP,PAPI_BR_PRC, \
             PAPI_TOT_INS,PAPI_FP_INS,PAPI_BR_INS,PAPI_VEC_INS,PAPI_TOT_CYC, \
             PAPI_L2_DCH,PAPI_L1_DCA,PAPI_L2_DCR,PAPI_L2_ICH,PAPI_L2_ICA,PAPI_L2_ICR, \
             PAPI_FML_INS,PAPI_FAD_INS,PAPI_FDV_INS,PAPI_FSQ_INS,PAPI_FP_OPS \
      cumulative=0 auto_pause=1
start name=syspapi_sampler interval=1000000



listen name=default xprt=sock port=412