version: "3.9"
services:
 server1:
   image: rahmanarin29/mincer:latest
   command: ["bash","-lc","sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
 server2:
   image: rahmanarin29/mincer:latest
   command: ["bash","-lc","sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
 client1:
   image: rahmanarin29/mincer:latest
   command: ["bash","-lc","sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
 client2:
   image: rahmanarin29/mincer:latest
   command: ["bash","-lc","sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
 client3:
   image: rahmanarin29/mincer:latest
   command: ["bash","-lc","sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
 client4:
   image: rahmanarin29/mincer:latest
   command: ["bash","-lc","sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
 server3:
   image: rahmanarin29/mincer:latest
   command: ["bash","-lc","sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netB]
 client5:
   image: rahmanarin29/mincer:latest
   command: ["bash","-lc","sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netB]
 client6:
   image: rahmanarin29/mincer:latest
   command: ["bash","-lc","sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netB]
 aggregator:
   image: rahmanarin29/mincer:latest
   command: ["bash","-lc","sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netAgg, netA, netB]
networks:
 netA:
   driver: overlay
   attachable: true
   ipam:
     config:
       - subnet: 10.80.0.0/24
 netB:
   driver: overlay
   attachable: true
   ipam:
     config:
       - subnet: 10.81.0.0/24
 netAgg:
   driver: overlay
   attachable: true
   ipam:
     config:
       - subnet: 10.82.0.0/24
 