version: "3.9"
configs:
 ldms_sampler_conf_v7:
   file: ./ldmsd.conf
 ldms_agg_conf_v7:
   file: ./ldmsd_agg.conf
 collect_py_v7:
   file: ./collect.py
 pcap_capture_sh_v2:                # NEW
   file: ./capture_pcap.sh
volumes:
 agg_data: {}
 pcap_data: {}                      # NEW
services:
 server1:
   image: rahmanarin29/mincer:latest
   environment: [LDMS_NODE=server1]
   command: ["bash","-lc","tr -d '\\r' < /etc/ldms/ldmsd.conf > /tmp/ldmsd.conf && /opt/ovis/sbin/ldmsd -c /tmp/ldmsd.conf & sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
   configs:
     - source: ldms_sampler_conf_v7
       target: /etc/ldms/ldmsd.conf
     - source: pcap_capture_sh_v2           # NEW
       target: /usr/local/bin/capture_pcap.sh
       mode: 0555
   volumes:
    - pcap_data:/pcap                      # NEW
   

 server2:
   image: rahmanarin29/mincer-server2
   environment: [LDMS_NODE=server2]
   command: ["bash","-lc","tr -d '\\r' < /etc/ldms/ldmsd.conf > /tmp/ldmsd.conf && /opt/ovis/sbin/ldmsd -c /tmp/ldmsd.conf & sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
   configs:
     - source: ldms_sampler_conf_v7
       target: /etc/ldms/ldmsd.conf
     - source: pcap_capture_sh_v2           # NEW
       target: /usr/local/bin/capture_pcap.sh
       mode: 0555
   volumes:
    - pcap_data:/pcap                      # NEW
 client1:
   image: rahmanarin29/mincer:latest
   environment: [LDMS_NODE=client1]
   command: ["bash","-lc","tr -d '\\r' < /etc/ldms/ldmsd.conf > /tmp/ldmsd.conf && /opt/ovis/sbin/ldmsd -c /tmp/ldmsd.conf & sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
   configs:
     - source: ldms_sampler_conf_v7
       target: /etc/ldms/ldmsd.conf
     - source: pcap_capture_sh_v2           # NEW
       target: /usr/local/bin/capture_pcap.sh
       mode: 0555
   volumes:
    - pcap_data:/pcap                      # NEW
 client2:
   image: rahmanarin29/mincer:latest
   environment: [LDMS_NODE=client2]
   command: ["bash","-lc","tr -d '\\r' < /etc/ldms/ldmsd.conf > /tmp/ldmsd.conf && /opt/ovis/sbin/ldmsd -c /tmp/ldmsd.conf & sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
   configs:
     - source: ldms_sampler_conf_v7
       target: /etc/ldms/ldmsd.conf
     - source: pcap_capture_sh_v2           # NEW
       target: /usr/local/bin/capture_pcap.sh
       mode: 0555
   volumes:
    - pcap_data:/pcap                      # NEW
 client3:
   image: rahmanarin29/mincer:latest
   environment: [LDMS_NODE=client3]
   command: ["bash","-lc","tr -d '\\r' < /etc/ldms/ldmsd.conf > /tmp/ldmsd.conf && /opt/ovis/sbin/ldmsd -c /tmp/ldmsd.conf & sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
   configs:
     - source: ldms_sampler_conf_v7
       target: /etc/ldms/ldmsd.conf
     - source: pcap_capture_sh_v2           # NEW
       target: /usr/local/bin/capture_pcap.sh
       mode: 0555
   volumes:
    - pcap_data:/pcap                      # NEW
 client4:
   image: rahmanarin29/mincer:latest
   environment: [LDMS_NODE=client4]
   command: ["bash","-lc","tr -d '\\r' < /etc/ldms/ldmsd.conf > /tmp/ldmsd.conf && /opt/ovis/sbin/ldmsd -c /tmp/ldmsd.conf & sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netA]
   configs:
     - source: ldms_sampler_conf_v7
       target: /etc/ldms/ldmsd.conf
     - source: pcap_capture_sh_v2           # NEW
       target: /usr/local/bin/capture_pcap.sh
       mode: 0555
   volumes:
    - pcap_data:/pcap                      # NEW
 server3:
   image: rahmanarin29/mincer:latest
   environment: [LDMS_NODE=server3]
   command: ["bash","-lc","tr -d '\\r' < /etc/ldms/ldmsd.conf > /tmp/ldmsd.conf && /opt/ovis/sbin/ldmsd -c /tmp/ldmsd.conf & sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netB]
   configs:
     - source: ldms_sampler_conf_v7
       target: /etc/ldms/ldmsd.conf
     - source: pcap_capture_sh_v2           # NEW
       target: /usr/local/bin/capture_pcap.sh
       mode: 0555
   volumes:
    - pcap_data:/pcap                      # NEW
 client5:
   image: rahmanarin29/mincer:latest
   environment: [LDMS_NODE=client5]
   command: ["bash","-lc","tr -d '\\r' < /etc/ldms/ldmsd.conf > /tmp/ldmsd.conf && /opt/ovis/sbin/ldmsd -c /tmp/ldmsd.conf & sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netB]
   configs:
     - source: ldms_sampler_conf_v7
       target: /etc/ldms/ldmsd.conf
     - source: pcap_capture_sh_v2           # NEW
       target: /usr/local/bin/capture_pcap.sh
       mode: 0555
   volumes:
    - pcap_data:/pcap                      # NEW
 client6:
   image: rahmanarin29/mincer:latest
   environment: [LDMS_NODE=client6]
   command: ["bash","-lc","tr -d '\\r' < /etc/ldms/ldmsd.conf > /tmp/ldmsd.conf && /opt/ovis/sbin/ldmsd -c /tmp/ldmsd.conf & sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netB]
   configs:
     - source: ldms_sampler_conf_v7
       target: /etc/ldms/ldmsd.conf
     - source: pcap_capture_sh_v2           # NEW
       target: /usr/local/bin/capture_pcap.sh
       mode: 0555
   volumes:
    - pcap_data:/pcap                      # NEW
 aggregator:
   image: rahmanarin29/mincer:latest
   environment:
     - TERM=xterm
     - PYTHONUNBUFFERED=1
     - LDMSD_MEM_SZ=128M
   # Start ldmsd and keep the container alive (no auto-running collect.py)
   command: ["bash","-lc","mkdir -p /data && tr -d '\\r' < /etc/ldms/ldmsd_agg.conf > /tmp/ldmsd_agg.conf && printf '\\n' >> /tmp/ldmsd_agg.conf && /opt/ovis/sbin/ldmsd -c /tmp/ldmsd_agg.conf -v INFO & sleep infinity"]
   cap_add: ["NET_ADMIN"]
   networks: [netAgg, netA, netB]
   configs:
     - source: ldms_agg_conf_v7
       target: /etc/ldms/ldmsd_agg.conf
     - source: collect_py_v7
       target: /opt/collector/collect.py
       mode: 0444
     - source: pcap_capture_sh_v2
       target: /usr/local/bin/capture_pcap.sh
       mode: 0555
   volumes:
     - agg_data:/data
     - pcap_data:/pcap
networks:
 netA:
   driver: overlay
   attachable: true
   ipam:
     config:
       - subnet: 10.80.0.0/24
 netB:
   driver: overlay
   attachable: true
   ipam:
     config:
       - subnet: 10.81.0.0/24
 netAgg:
   driver: overlay
   attachable: true
   ipam:
     config:
       - subnet: 10.82.0.0/24